export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const USER_LOADING = 'USER_LOADING';
export const USER_SUCCESS_LOGGED = 'USER_SUCCESS_LOGGED';
export const USER_SUCCESS_NOT_LOGGED = 'USER_SUCCESS_NOT_LOGGED';
export const USER_FAIL = 'USER_FAIL';