export const ALERT_SET = 'ALERT_SET';
export const ALERT_SHOW = 'ALERT_SHOW';
export const ALERT_HIDE = 'ALERT_HIDE';
export const ALERT_RESET = 'ALERT_RESET';

export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const USER_LOADING = 'USER_LOADING';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAIL = 'USER_FAIL';
export const USER_RESET = 'USER_RESET';

export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const EMAIL_LOADING = 'EMAIL_LOADING';
export const EMAIL_SUCCESS = 'EMAIL_SUCCESS';
export const EMAIL_FAIL = 'EMAIL_FAIL';

export const PASSWORD_LOADING = 'PASSWORD_LOADING';
export const PASSWORD_SUCCESS = 'PASSWORD_SUCCESS';
export const PASSWORD_FAIL = 'PASSWORD_FAIL';

export const RECORD_LOADING = 'RECORD_LOADING';
export const RECORD_SUCCESS = 'RECORD_SUCCESS';
export const RECORD_FAIL = 'RECORD_FAIL';

export const RECORD_LIST_LOADING = 'RECORD_LIST_LOADING';
export const RECORD_LIST_SUCCESS = 'RECORD_LIST_SUCCESS';
export const RECORD_LIST_FAIL = 'RECORD_LIST_FAIL';

export const PLAYER_SET_INSTANCE = 'PLAYER_SET_INSTANCE';
export const PLAYER_ADD_TRACK = 'PLAYER_ADD_TRACK';
export const PLAYER_PLAY_TRACK = 'PLAYER_PLAY_TRACK';
export const PLAYER_PAUSE_TRACK = 'PLAYER_PAUSE_TRACK';
export const PLAYER_RESUME_TRACK = 'PLAYER_RESUME_TRACK';